import React, { useState, useEffect } from "react";
import { addTask } from "../services/taskServices";

const CreateTask = () => {
  /* CREATE 'CreateTask' COMPONENT */

  //input text
  const [taskName, setTaskName] = useState("");

  const handleInputChange = (event) => {
    setTaskName(event.target.value);
  };

  const handleCreateTask = (event) => {
    /*
    sends post request to db
    creates: task = {task:<task>, _id:<auto-generated by mongoose>} 
    */
    event.preventDefault();
    if (taskName.length < 1) {
      alert("Can't create an empty task!");
      return false;
    }

    //clear input and handle post request
    //addTask(<string>)
    addTask(taskName).then((res) => {
      setTaskName("");
      alert(`Task: ${res.data.task} has been created!`);
    });
  };

  return (
    <div className="d-flex flex-column align-items-center pt-5">
      <h1>Create a task</h1>
      <input
        type="text"
        placeholder="Type your task here!"
        maxLength={30}
        onChange={handleInputChange}
        value={taskName}
      ></input>
      <button onClick={handleCreateTask}>Create task!</button>
    </div>
  );
};

export default CreateTask;
